### ISSUE TITLE
Finetuning for the TVR task

### ISSUE THREAD

**Issue by Unified-Robots** [linjieli222/HERO#11]
I only have two gpu in my computer. When I use the command " horovodrun -np 2 python train_vcmr.py --config config/train-tvr-8gpu.json', the code meets deadlock. I attach the output here. How to solve this issue? 

[1,0]<stderr>:02/01/2021 22:11:30 - INFO - __main__ -   Loading tvr train dataset /video/tv
[1,0]<stderr>:02/01/2021 22:11:33 - INFO - __main__ -   87153 samples loaded
[1,1]<stderr>:
[1,0]<stderr>:02/01/2021 22:11:33 - INFO - __main__ -   Loading tvr validation dataset/video/tv
[1,0]<stderr>:02/01/2021 22:11:33 - INFO - __main__ -   10895 samples loaded
[1,0]<stderr>:02/01/2021 22:11:33 - INFO - __main__ -   Loading Inference Dataset /txt/tvr_val.db (val)
[1,0]<stderr>:02/01/2021 22:11:34 - INFO - model.model -   Model config:
[1,0]<stderr>:02/01/2021 22:11:34 - INFO - model.model -        Cross-Modal Transformer config: {
[1,0]<stderr>:  "attention_probs_dropout_prob": 0.1,
[1,0]<stderr>:  "hidden_act": "gelu",
[1,0]<stderr>:  "hidden_dropout_prob": 0.1,
[1,0]<stderr>:  "hidden_size": 768,
[1,0]<stderr>:  "initializer_range": 0.02,
[1,0]<stderr>:  "intermediate_size": 3072,
[1,0]<stderr>:  "layer_norm_eps": 1e-12,
[1,0]<stderr>:  "max_position_embeddings": 514,
[1,0]<stderr>:  "num_attention_heads": 12,
[1,0]<stderr>:  "num_hidden_layers": 6,
[1,0]<stderr>:  "output_attentions": false,
[1,0]<stderr>:  "output_hidden_states": false,
[1,0]<stderr>:  "type_vocab_size": 2,
[1,0]<stderr>:  "vocab_size": 50272
[1,0]<stderr>:}
[1,0]<stderr>:
[1,0]<stderr>:02/01/2021 22:11:34 - INFO - model.model -        Temporal Transformer config: {
[1,0]<stderr>:  "attention_probs_dropout_prob": 0.1,
[1,0]<stderr>:  "hidden_act": "gelu",
[1,0]<stderr>:  "hidden_dropout_prob": 0.1,
[1,0]<stderr>:  "hidden_size": 768,
[1,0]<stderr>:  "initializer_range": 0.02,
[1,0]<stderr>:  "intermediate_size": 3072,
[1,0]<stderr>:  "layer_norm_eps": 1e-12,
[1,0]<stderr>:  "max_position_embeddings": 514,
[1,0]<stderr>:  "num_attention_heads": 12,
[1,0]<stderr>:  "num_hidden_layers": 3,
[1,0]<stderr>:  "output_attentions": false,
[1,0]<stderr>:  "output_hidden_states": false,
[1,0]<stderr>:  "type_vocab_size": 2,
[1,0]<stderr>:  "vocab_size": -1
[1,0]<stderr>:}
[1,0]<stderr>:
[1,0]<stderr>:02/01/2021 22:11:34 - INFO - model.model -        QueryEncoder config: {
[1,0]<stderr>:  "attention_probs_dropout_prob": 0.1,
[1,0]<stderr>:  "hidden_act": "gelu",
[1,0]<stderr>:  "hidden_dropout_prob": 0.1,
[1,0]<stderr>:  "hidden_size": 768,
[1,0]<stderr>:  "initializer_range": 0.02,
[1,0]<stderr>:  "intermediate_size": 3072,
[1,0]<stderr>:  "layer_norm_eps": 1e-12,
[1,0]<stderr>:  "max_position_embeddings": 514,
[1,0]<stderr>:  "num_attention_heads": 12,
[1,0]<stderr>:  "num_hidden_layers": 0,
[1,0]<stderr>:  "output_attentions": false,
[1,0]<stderr>:  "output_hidden_states": false,
[1,0]<stderr>:  "type_vocab_size": 1,
[1,0]<stderr>:  "vocab_size": 50272
[1,0]<stderr>:}
[1,0]<stderr>:
[1,0]<stderr>:02/01/2021 22:11:34 - INFO - model.model -        Decoder Transformer config: None
[1,1]<stderr>:02/01/2021 22:11:34 - INFO - model.model -   Model config:
[1,1]<stderr>:02/01/2021 22:11:34 - INFO - model.model -        Cross-Modal Transformer config: {
[1,1]<stderr>:  "attention_probs_dropout_prob": 0.1,
[1,1]<stderr>:  "hidden_act": "gelu",
[1,1]<stderr>:  "hidden_dropout_prob": 0.1,
[1,1]<stderr>:  "hidden_size": 768,
[1,1]<stderr>:  "initializer_range": 0.02,
[1,1]<stderr>:  "intermediate_size": 3072,
[1,1]<stderr>:  "layer_norm_eps": 1e-12,
[1,1]<stderr>:  "max_position_embeddings": 514,
[1,1]<stderr>:  "num_attention_heads": 12,
[1,1]<stderr>:  "num_hidden_layers": 6,
[1,1]<stderr>:  "output_attentions": false,
[1,1]<stderr>:  "output_hidden_states": false,
[1,1]<stderr>:  "type_vocab_size": 2,
[1,1]<stderr>:  "vocab_size": 50272
[1,1]<stderr>:}
[1,1]<stderr>:
[1,1]<stderr>:02/01/2021 22:11:34 - INFO - model.model -        Temporal Transformer config: {
[1,1]<stderr>:  "attention_probs_dropout_prob": 0.1,
[1,1]<stderr>:  "hidden_act": "gelu",
[1,1]<stderr>:  "hidden_dropout_prob": 0.1,
[1,1]<stderr>:  "hidden_size": 768,
[1,1]<stderr>:  "initializer_range": 0.02,
[1,1]<stderr>:  "intermediate_size": 3072,
[1,1]<stderr>:  "layer_norm_eps": 1e-12,
[1,1]<stderr>:  "max_position_embeddings": 514,
[1,1]<stderr>:  "num_attention_heads": 12,
[1,1]<stderr>:  "num_hidden_layers": 3,
[1,1]<stderr>:  "output_attentions": false,
[1,1]<stderr>:  "output_hidden_states": false,
[1,1]<stderr>:  "type_vocab_size": 2,
[1,1]<stderr>:  "vocab_size": -1
[1,1]<stderr>:}
[1,1]<stderr>:
[1,1]<stderr>:02/01/2021 22:11:34 - INFO - model.model -        QueryEncoder config: {
[1,1]<stderr>:  "attention_probs_dropout_prob": 0.1,
[1,1]<stderr>:  "hidden_act": "gelu",
[1,1]<stderr>:  "hidden_dropout_prob": 0.1,
[1,1]<stderr>:  "hidden_size": 768,
[1,1]<stderr>:  "initializer_range": 0.02,
[1,1]<stderr>:  "intermediate_size": 3072,
[1,1]<stderr>:  "layer_norm_eps": 1e-12,
[1,1]<stderr>:  "max_position_embeddings": 514,
[1,1]<stderr>:  "num_attention_heads": 12,
[1,1]<stderr>:  "num_hidden_layers": 0,
[1,1]<stderr>:  "output_attentions": false,
[1,1]<stderr>:  "output_hidden_states": false,
[1,1]<stderr>:  "type_vocab_size": 1,
[1,1]<stderr>:  "vocab_size": 50272
[1,1]<stderr>:}
[1,1]<stderr>:
[1,1]<stderr>:02/01/2021 22:11:34 - INFO - model.model -        Decoder Transformer config: None
[1,1]<stderr>:02/01/2021 22:11:45 - INFO - model.modeling_utils -   Weights from pretrained model not used in HeroForVcmr: ['vocab_padded']
[1,0]<stderr>:02/01/2021 22:11:45 - INFO - model.modeling_utils -   Weights from pretrained model not used in HeroForVcmr: ['vocab_padded']
[1,1]<stdout>:Selected optimization level O2:  FP16 training with FP32 batchnorm and FP32 master weights.
[1,1]<stdout>:
[1,1]<stdout>:Defaults for this optimization level are:
[1,1]<stdout>:enabled                : True
[1,1]<stdout>:opt_level              : O2
[1,1]<stdout>:cast_model_type        : torch.float16
[1,1]<stdout>:patch_torch_functions  : False
[1,1]<stdout>:keep_batchnorm_fp32    : True
[1,1]<stdout>:master_weights         : True
[1,1]<stdout>:loss_scale             : dynamic
[1,1]<stdout>:Processing user overrides (additional kwargs that are not None)...
[1,1]<stdout>:After processing overrides, optimization options are:
[1,1]<stdout>:enabled                : True
[1,1]<stdout>:opt_level              : O2
[1,1]<stdout>:cast_model_type        : torch.float16
[1,1]<stdout>:patch_torch_functions  : False
[1,1]<stdout>:keep_batchnorm_fp32    : True
[1,1]<stdout>:master_weights         : True
[1,1]<stdout>:loss_scale             : dynamic
[1,0]<stdout>:Selected optimization level O2:  FP16 training with FP32 batchnorm and FP32 master weights.
[1,0]<stdout>:
[1,0]<stdout>:Defaults for this optimization level are:
[1,0]<stdout>:enabled                : True
[1,0]<stdout>:opt_level              : O2
[1,0]<stdout>:cast_model_type        : torch.float16
[1,0]<stdout>:patch_torch_functions  : False
[1,0]<stdout>:keep_batchnorm_fp32    : True
[1,0]<stdout>:master_weights         : True
[1,0]<stdout>:loss_scale             : dynamic
[1,0]<stdout>:Processing user overrides (additional kwargs that are not None)...
[1,0]<stdout>:After processing overrides, optimization options are:
[1,0]<stdout>:enabled                : True
[1,0]<stdout>:opt_level              : O2
[1,0]<stdout>:cast_model_type        : torch.float16
[1,0]<stdout>:patch_torch_functions  : False
[1,0]<stdout>:keep_batchnorm_fp32    : True
[1,0]<stdout>:master_weights         : True
[1,0]<stdout>:loss_scale             : dynamic
[1,1]<stdout>:restorer is finished
[1,0]<stdout>:restorer is finished
[1,0]<stderr>:02/01/2021 22:11:46 - INFO - __main__ -   Waiting on git info....
[1,0]<stderr>:fatal: not a git repository (or any parent up to mount point /)
[1,0]<stderr>:Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
[1,0]<stderr>:02/01/2021 22:11:46 - INFO - __main__ -   Git branch: 
[1,0]<stderr>:fatal: not a git repository (or any parent up to mount point /)
[1,0]<stderr>:Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
[1,0]<stderr>:02/01/2021 22:11:46 - INFO - __main__ -   Git SHA: 
[1,0]<stderr>:fatal: not a git repository (or any parent up to mount point /)
[1,0]<stderr>:Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
[1,0]<stderr>:02/01/2021 22:11:47 - ERROR - __main__ -   Command '['git', 'status', '--short']' returned non-zero exit status 128.
[1,0]<stderr>:Traceback (most recent call last):
[1,0]<stderr>:  File "/src/utils/save.py", line 51, in save_training_meta
[1,0]<stderr>:    cwd=git_dir, universal_newlines=True).strip()
[1,0]<stderr>:  File "/opt/conda/lib/python3.6/subprocess.py", line 356, in check_output
[1,0]<stderr>:    **kwargs).stdout
[1,0]<stderr>:  File "/opt/conda/lib/python3.6/subprocess.py", line 438, in run
[1,0]<stderr>:    output=stdout, stderr=stderr)
[1,0]<stderr>:subprocess.CalledProcessError: Command '['git', 'status', '--short']' returned non-zero exit status 128.
[1,0]<stderr>:02/01/2021 22:11:47 - WARNING - __main__ -   Git info not found. Saving code into zip instead...
[1,0]<stderr>:02/01/2021 22:11:47 - INFO - __main__ -   Saving code from /src to /storage/tvr_default/code.zip...
[1,0]<stderr>:[2021-02-01 22:13:23.215038: W horovod/common/stall_inspector.cc:105] One or more tensors were submitted to be reduced, gathered or broadcasted by subset of ranks and are waiting for remainder of ranks for more than 60 seconds. This may indicate that different ranks are trying to submit different tensors or that only subset of ranks is submitting tensors, which will cause deadlock. 
[1,0]<stderr>:Stalled ranks:
[1,0]<stderr>:0: [allgather.noname.40]
[1,0]<stderr>:[2021-02-01 22:14:23.216625: W horovod/common/stall_inspector.cc:105] One or more tensors were submitted to be reduced, gathered or broadcasted by subset of ranks and are waiting for remainder of ranks for more than 60 seconds. This may indicate that different ranks are trying to submit different tensors or that only subset of ranks is submitting tensors, which will cause deadlock. 
[1,0]<stderr>:Stalled ranks:
[1,0]<stderr>:0: [allgather.noname.40][1,0]<stderr>:
[1,0]<stderr>:[2021-02-01 22:15:23.218786: W horovod/common/stall_inspector.cc:105] One or more tensors were submitted to be reduced, gathered or broadcasted by subset of ranks and are waiting for remainder of ranks for more than 60 seconds. This may indicate that different ranks are trying to submit different tensors or that only subset of ranks is submitting tensors, which will cause deadlock. 
[1,0]<stderr>:Stalled ranks:
[1,0]<stderr>:0: [allgather.noname.40]
[1,0]<stderr>:[2021-02-01 22:16:23.223750: W horovod/common/stall_inspector.cc:105] One or more tensors were submitted to be reduced, gathered or broadcasted by subset of ranks and are waiting for remainder of ranks for more than 60 seconds. This may indicate that different ranks are trying to submit different tensors or that only subset of ranks is submitting tensors, which will cause deadlock. 
[1,0]<stderr>:Stalled ranks:
[1,0]<stderr>:0: [allgather.noname.40]

**Comment by Unified-Robots** [comment]
`[1,1]<stdout>:Defaults for this optimization level are:
[1,1]<stdout>:enabled                : True
[1,1]<stdout>:opt_level              : O2
[1,1]<stdout>:cast_model_type        : torch.float16
[1,1]<stdout>:patch_torch_functions  : False
[1,1]<stdout>:keep_batchnorm_fp32    : True
[1,1]<stdout>:master_weights         : True
[1,1]<stdout>:loss_scale             : dynamic
[1,1]<stdout>:Processing user overrides (additional kwargs that are not None)...
[1,1]<stdout>:After processing overrides, optimization options are:
[1,1]<stdout>:enabled                : True
[1,1]<stdout>:opt_level              : O2
[1,1]<stdout>:cast_model_type        : torch.float16
[1,1]<stdout>:patch_torch_functions  : False
[1,1]<stdout>:keep_batchnorm_fp32    : True
[1,1]<stdout>:master_weights         : True
[1,1]<stdout>:loss_scale             : dynamic
[1,0]<stdout>:Selected optimization level O2:  FP16 training with FP32 batchnorm and FP32 master weights.
[1,0]<stdout>:
[1,0]<stdout>:Defaults for this optimization level are:
[1,0]<stdout>:enabled                : True
[1,0]<stdout>:opt_level              : O2
[1,0]<stdout>:cast_model_type        : torch.float16
[1,0]<stdout>:patch_torch_functions  : False
[1,0]<stdout>:keep_batchnorm_fp32    : True
[1,0]<stdout>:master_weights         : True
[1,0]<stdout>:loss_scale             : dynamic
[1,0]<stdout>:Processing user overrides (additional kwargs that are not None)...
[1,0]<stdout>:After processing overrides, optimization options are:
[1,0]<stdout>:enabled                : True
[1,0]<stdout>:opt_level              : O2
[1,0]<stdout>:cast_model_type        : torch.float16
[1,0]<stdout>:patch_torch_functions  : False
[1,0]<stdout>:keep_batchnorm_fp32    : True
[1,0]<stdout>:master_weights         : True
[1,0]<stdout>:loss_scale             : dynamic
[1,1]<stdout>:restorer is finished
[1,0]<stdout>:restorer is finished
[1,0]<stderr>:02/01/2021 22:11:46 - INFO - __main__ -   Waiting on git info....
[1,0]<stderr>:fatal: not a git repository (or any parent up to mount point /)
[1,0]<stderr>:Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
[1,0]<stderr>:02/01/2021 22:11:46 - INFO - __main__ -   Git branch: 
[1,0]<stderr>:fatal: not a git repository (or any parent up to mount point /)
[1,0]<stderr>:Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
[1,0]<stderr>:02/01/2021 22:11:46 - INFO - __main__ -   Git SHA: 
[1,0]<stderr>:fatal: not a git repository (or any parent up to mount point /)
[1,0]<stderr>:Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
[1,0]<stderr>:02/01/2021 22:11:47 - ERROR - __main__ -   Command '['git', 'status', '--short']' returned non-zero exit status 128.
[1,0]<stderr>:Traceback (most recent call last):
[1,0]<stderr>:  File "/src/utils/save.py", line 51, in save_training_meta
[1,0]<stderr>:    cwd=git_dir, universal_newlines=True).strip()
[1,0]<stderr>:  File "/opt/conda/lib/python3.6/subprocess.py", line 356, in check_output
[1,0]<stderr>:    **kwargs).stdout
[1,0]<stderr>:  File "/opt/conda/lib/python3.6/subprocess.py", line 438, in run
[1,0]<stderr>:    output=stdout, stderr=stderr)
[1,0]<stderr>:subprocess.CalledProcessError: Command '['git', 'status', '--short']' returned non-zero exit status 128.
[1,0]<stderr>:02/01/2021 22:11:47 - WARNING - __main__ -   Git info not found. Saving code into zip instead...
[1,0]<stderr>:02/01/2021 22:11:47 - INFO - __main__ -   Saving code from /src to /storage/tvr_default/code.zip...
[1,0]<stderr>:[2021-02-01 22:13:23.215038: W horovod/common/stall_inspector.cc:105] One or more tensors were submitted to be reduced, gathered or broadcasted by subset of ranks and are waiting for remainder of ranks for more than 60 seconds. This may indicate that different ranks are trying to submit different tensors or that only subset of ranks is submitting tensors, which will cause deadlock. 
[1,0]<stderr>:Stalled ranks:
[1,0]<stderr>:0: [allgather.noname.40]
[1,0]<stderr>:[2021-02-01 22:14:23.216625: W horovod/common/stall_inspector.cc:105] One or more tensors were submitted to be reduced, gathered or broadcasted by subset of ranks and are waiting for remainder of ranks for more than 60 seconds. This may indicate that different ranks are trying to submit different tensors or that only subset of ranks is submitting tensors, which will cause deadlock. 
[1,0]<stderr>:Stalled ranks:
[1,0]<stderr>:0: [allgather.noname.40][1,0]<stderr>:
[1,0]<stderr>:[2021-02-01 22:15:23.218786: W horovod/common/stall_inspector.cc:105] One or more tensors were submitted to be reduced, gathered or broadcasted by subset of ranks and are waiting for remainder of ranks for more than 60 seconds. This may indicate that different ranks are trying to submit different tensors or that only subset of ranks is submitting tensors, which will cause deadlock. 
[1,0]<stderr>:Stalled ranks:
[1,0]<stderr>:0: [allgather.noname.40]
[1,0]<stderr>:[2021-02-01 22:16:23.223750: W horovod/common/stall_inspector.cc:105] One or more tensors were submitted to be reduced, gathered or broadcasted by subset of ranks and are waiting for remainder of ranks for more than 60 seconds. This may indicate that different ranks are trying to submit different tensors or that only subset of ranks is submitting tensors, which will cause deadlock. 
[1,0]<stderr>:Stalled ranks:
[1,0]<stderr>:0: [allgather.noname.40]
`

**Comment by Unified-Robots** [comment]
``
[1,0]<stderr>:02/01/2021 22:11:30 - INFO - __main__ -   Loading tvr train dataset /video/tv
[1,0]<stderr>:02/01/2021 22:11:33 - INFO - __main__ -   87153 samples loaded
[1,1]<stderr>:
[1,0]<stderr>:02/01/2021 22:11:33 - INFO - __main__ -   Loading tvr validation dataset/video/tv
[1,0]<stderr>:02/01/2021 22:11:33 - INFO - __main__ -   10895 samples loaded
[1,0]<stderr>:02/01/2021 22:11:33 - INFO - __main__ -   Loading Inference Dataset /txt/tvr_val.db (val)
[1,0]<stderr>:02/01/2021 22:11:34 - INFO - model.model -   Model config:
[1,0]<stderr>:02/01/2021 22:11:34 - INFO - model.model -        Cross-Modal Transformer config: {
[1,0]<stderr>:  "attention_probs_dropout_prob": 0.1,
[1,0]<stderr>:  "hidden_act": "gelu",
[1,0]<stderr>:  "hidden_dropout_prob": 0.1,
[1,0]<stderr>:  "hidden_size": 768,
[1,0]<stderr>:  "initializer_range": 0.02,
[1,0]<stderr>:  "intermediate_size": 3072,
[1,0]<stderr>:  "layer_norm_eps": 1e-12,
[1,0]<stderr>:  "max_position_embeddings": 514,
[1,0]<stderr>:  "num_attention_heads": 12,
[1,0]<stderr>:  "num_hidden_layers": 6,
[1,0]<stderr>:  "output_attentions": false,
[1,0]<stderr>:  "output_hidden_states": false,
[1,0]<stderr>:  "type_vocab_size": 2,
[1,0]<stderr>:  "vocab_size": 50272
[1,0]<stderr>:}
[1,0]<stderr>:
[1,0]<stderr>:02/01/2021 22:11:34 - INFO - model.model -        Temporal Transformer config: {
[1,0]<stderr>:  "attention_probs_dropout_prob": 0.1,
[1,0]<stderr>:  "hidden_act": "gelu",
[1,0]<stderr>:  "hidden_dropout_prob": 0.1,
[1,0]<stderr>:  "hidden_size": 768,
[1,0]<stderr>:  "initializer_range": 0.02,
[1,0]<stderr>:  "intermediate_size": 3072,
[1,0]<stderr>:  "layer_norm_eps": 1e-12,
[1,0]<stderr>:  "max_position_embeddings": 514,
[1,0]<stderr>:  "num_attention_heads": 12,
[1,0]<stderr>:  "num_hidden_layers": 3,
[1,0]<stderr>:  "output_attentions": false,
[1,0]<stderr>:  "output_hidden_states": false,
[1,0]<stderr>:  "type_vocab_size": 2,
[1,0]<stderr>:  "vocab_size": -1
[1,0]<stderr>:}
[1,0]<stderr>:
[1,0]<stderr>:02/01/2021 22:11:34 - INFO - model.model -        QueryEncoder config: {
[1,0]<stderr>:  "attention_probs_dropout_prob": 0.1,
[1,0]<stderr>:  "hidden_act": "gelu",
[1,0]<stderr>:  "hidden_dropout_prob": 0.1,
[1,0]<stderr>:  "hidden_size": 768,
[1,0]<stderr>:  "initializer_range": 0.02,
[1,0]<stderr>:  "intermediate_size": 3072,
[1,0]<stderr>:  "layer_norm_eps": 1e-12,
[1,0]<stderr>:  "max_position_embeddings": 514,
[1,0]<stderr>:  "num_attention_heads": 12,
[1,0]<stderr>:  "num_hidden_layers": 0,
[1,0]<stderr>:  "output_attentions": false,
[1,0]<stderr>:  "output_hidden_states": false,
[1,0]<stderr>:  "type_vocab_size": 1,
[1,0]<stderr>:  "vocab_size": 50272
[1,0]<stderr>:}
[1,0]<stderr>:
[1,0]<stderr>:02/01/2021 22:11:34 - INFO - model.model -        Decoder Transformer config: None
[1,1]<stderr>:02/01/2021 22:11:34 - INFO - model.model -   Model config:
[1,1]<stderr>:02/01/2021 22:11:34 - INFO - model.model -        Cross-Modal Transformer config: {
[1,1]<stderr>:  "attention_probs_dropout_prob": 0.1,
[1,1]<stderr>:  "hidden_act": "gelu",
[1,1]<stderr>:  "hidden_dropout_prob": 0.1,
[1,1]<stderr>:  "hidden_size": 768,
[1,1]<stderr>:  "initializer_range": 0.02,
[1,1]<stderr>:  "intermediate_size": 3072,
[1,1]<stderr>:  "layer_norm_eps": 1e-12,
[1,1]<stderr>:  "max_position_embeddings": 514,
[1,1]<stderr>:  "num_attention_heads": 12,
[1,1]<stderr>:  "num_hidden_layers": 6,
[1,1]<stderr>:  "output_attentions": false,
[1,1]<stderr>:  "output_hidden_states": false,
[1,1]<stderr>:  "type_vocab_size": 2,
[1,1]<stderr>:  "vocab_size": 50272
[1,1]<stderr>:}
[1,1]<stderr>:
[1,1]<stderr>:02/01/2021 22:11:34 - INFO - model.model -        Temporal Transformer config: {
[1,1]<stderr>:  "attention_probs_dropout_prob": 0.1,
[1,1]<stderr>:  "hidden_act": "gelu",
[1,1]<stderr>:  "hidden_dropout_prob": 0.1,
[1,1]<stderr>:  "hidden_size": 768,
[1,1]<stderr>:  "initializer_range": 0.02,
[1,1]<stderr>:  "intermediate_size": 3072,
[1,1]<stderr>:  "layer_norm_eps": 1e-12,
[1,1]<stderr>:  "max_position_embeddings": 514,
[1,1]<stderr>:  "num_attention_heads": 12,
[1,1]<stderr>:  "num_hidden_layers": 3,
[1,1]<stderr>:  "output_attentions": false,
[1,1]<stderr>:  "output_hidden_states": false,
[1,1]<stderr>:  "type_vocab_size": 2,
[1,1]<stderr>:  "vocab_size": -1
[1,1]<stderr>:}
[1,1]<stderr>:
[1,1]<stderr>:02/01/2021 22:11:34 - INFO - model.model -        QueryEncoder config: {
[1,1]<stderr>:  "attention_probs_dropout_prob": 0.1,
[1,1]<stderr>:  "hidden_act": "gelu",
[1,1]<stderr>:  "hidden_dropout_prob": 0.1,
[1,1]<stderr>:  "hidden_size": 768,
[1,1]<stderr>:  "initializer_range": 0.02,
[1,1]<stderr>:  "intermediate_size": 3072,
[1,1]<stderr>:  "layer_norm_eps": 1e-12,
[1,1]<stderr>:  "max_position_embeddings": 514,
[1,1]<stderr>:  "num_attention_heads": 12,
[1,1]<stderr>:  "num_hidden_layers": 0,
[1,1]<stderr>:  "output_attentions": false,
[1,1]<stderr>:  "output_hidden_states": false,
[1,1]<stderr>:  "type_vocab_size": 1,
[1,1]<stderr>:  "vocab_size": 50272
[1,1]<stderr>:}
[1,1]<stderr>:
[1,1]<stderr>:02/01/2021 22:11:34 - INFO - model.model -        Decoder Transformer config: None
[1,1]<stderr>:02/01/2021 22:11:45 - INFO - model.modeling_utils -   Weights from pretrained model not used in HeroForVcmr: ['vocab_padded']
[1,0]<stderr>:02/01/2021 22:11:45 - INFO - model.modeling_utils -   Weights from pretrained model not used in HeroForVcmr: ['vocab_padded']
[1,1]<stdout>:Selected optimization level O2:  FP16 training with FP32 batchnorm and FP32 master weights.
[1,1]<stdout>:
[1,1]<stdout>:Defaults for this optimization level are:
[1,1]<stdout>:enabled                : True
[1,1]<stdout>:opt_level              : O2
[1,1]<stdout>:cast_model_type        : torch.float16
[1,1]<stdout>:patch_torch_functions  : False
[1,1]<stdout>:keep_batchnorm_fp32    : True
[1,1]<stdout>:master_weights         : True
[1,1]<stdout>:loss_scale             : dynamic
[1,1]<stdout>:Processing user overrides (additional kwargs that are not None)...
[1,1]<stdout>:After processing overrides, optimization options are:
[1,1]<stdout>:enabled                : True
[1,1]<stdout>:opt_level              : O2
[1,1]<stdout>:cast_model_type        : torch.float16
[1,1]<stdout>:patch_torch_functions  : False
[1,1]<stdout>:keep_batchnorm_fp32    : True
[1,1]<stdout>:master_weights         : True
[1,1]<stdout>:loss_scale             : dynamic
[1,0]<stdout>:Selected optimization level O2:  FP16 training with FP32 batchnorm and FP32 master weights.
[1,0]<stdout>:
[1,0]<stdout>:Defaults for this optimization level are:
[1,0]<stdout>:enabled                : True
[1,0]<stdout>:opt_level              : O2
[1,0]<stdout>:cast_model_type        : torch.float16
[1,0]<stdout>:patch_torch_functions  : False
[1,0]<stdout>:keep_batchnorm_fp32    : True
[1,0]<stdout>:master_weights         : True
[1,0]<stdout>:loss_scale             : dynamic
[1,0]<stdout>:Processing user overrides (additional kwargs that are not None)...
[1,0]<stdout>:After processing overrides, optimization options are:
[1,0]<stdout>:enabled                : True
[1,0]<stdout>:opt_level              : O2
[1,0]<stdout>:cast_model_type        : torch.float16
[1,0]<stdout>:patch_torch_functions  : False
[1,0]<stdout>:keep_batchnorm_fp32    : True
[1,0]<stdout>:master_weights         : True
[1,0]<stdout>:loss_scale             : dynamic
[1,1]<stdout>:restorer is finished
[1,0]<stdout>:restorer is finished
[1,0]<stderr>:02/01/2021 22:11:46 - INFO - __main__ -   Waiting on git info....
[1,0]<stderr>:fatal: not a git repository (or any parent up to mount point /)
[1,0]<stderr>:Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
[1,0]<stderr>:02/01/2021 22:11:46 - INFO - __main__ -   Git branch: 
[1,0]<stderr>:fatal: not a git repository (or any parent up to mount point /)
[1,0]<stderr>:Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
[1,0]<stderr>:02/01/2021 22:11:46 - INFO - __main__ -   Git SHA: 
[1,0]<stderr>:fatal: not a git repository (or any parent up to mount point /)
[1,0]<stderr>:Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
[1,0]<stderr>:02/01/2021 22:11:47 - ERROR - __main__ -   Command '['git', 'status', '--short']' returned non-zero exit status 128.
[1,0]<stderr>:Traceback (most recent call last):
[1,0]<stderr>:  File "/src/utils/save.py", line 51, in save_training_meta
[1,0]<stderr>:    cwd=git_dir, universal_newlines=True).strip()
[1,0]<stderr>:  File "/opt/conda/lib/python3.6/subprocess.py", line 356, in check_output
[1,0]<stderr>:    **kwargs).stdout
[1,0]<stderr>:  File "/opt/conda/lib/python3.6/subprocess.py", line 438, in run
[1,0]<stderr>:    output=stdout, stderr=stderr)
[1,0]<stderr>:subprocess.CalledProcessError: Command '['git', 'status', '--short']' returned non-zero exit status 128.
[1,0]<stderr>:02/01/2021 22:11:47 - WARNING - __main__ -   Git info not found. Saving code into zip instead...
[1,0]<stderr>:02/01/2021 22:11:47 - INFO - __main__ -   Saving code from /src to /storage/tvr_default/code.zip...
[1,0]<stderr>:[2021-02-01 22:13:23.215038: W horovod/common/stall_inspector.cc:105] One or more tensors were submitted to be reduced, gathered or broadcasted by subset of ranks and are waiting for remainder of ranks for more than 60 seconds. This may indicate that different ranks are trying to submit different tensors or that only subset of ranks is submitting tensors, which will cause deadlock. 
[1,0]<stderr>:Stalled ranks:
[1,0]<stderr>:0: [allgather.noname.40]
[1,0]<stderr>:[2021-02-01 22:14:23.216625: W horovod/common/stall_inspector.cc:105] One or more tensors were submitted to be reduced, gathered or broadcasted by subset of ranks and are waiting for remainder of ranks for more than 60 seconds. This may indicate that different ranks are trying to submit different tensors or that only subset of ranks is submitting tensors, which will cause deadlock. 
[1,0]<stderr>:Stalled ranks:
[1,0]<stderr>:0: [allgather.noname.40][1,0]<stderr>:
[1,0]<stderr>:[2021-02-01 22:15:23.218786: W horovod/common/stall_inspector.cc:105] One or more tensors were submitted to be reduced, gathered or broadcasted by subset of ranks and are waiting for remainder of ranks for more than 60 seconds. This may indicate that different ranks are trying to submit different tensors or that only subset of ranks is submitting tensors, which will cause deadlock. 
[1,0]<stderr>:Stalled ranks:
[1,0]<stderr>:0: [allgather.noname.40]
[1,0]<stderr>:[2021-02-01 22:16:23.223750: W horovod/common/stall_inspector.cc:105] One or more tensors were submitted to be reduced, gathered or broadcasted by subset of ranks and are waiting for remainder of ranks for more than 60 seconds. This may indicate that different ranks are trying to submit different tensors or that only subset of ranks is submitting tensors, which will cause deadlock. 
[1,0]<stderr>:Stalled ranks:
[1,0]<stderr>:0: [allgather.noname.40]

**Comment by linjieli222** [comment]
Hi,

Thanks for your interests in this project. During our experiments, we have observed the same error a few times. However, the error is not reproducible. When we repeat the exact experiment, the training runs smoothly. As the appearance of this error is rare and random at our end, we do not have any insight on why it was happening. You can also look into horovod repo, they may provide a more insightful explanation.

A quick fix is to run your experiments with 1 gpu. However,  it may results in lower performance and slower speed.

**Comment by Unified-Robots** [comment]
@linjieli222 OK, thanks for your reply. This problem may be related with our hardware. I run the experiments on single gpu, and it is fine. I have another request. Could you provide us a subset of **data for pre-training**? The code is somewhat complicated...

**Comment by linjieli222** [comment]
You can use TV dataset to conduct a relative "smaller"  pre-training experiment.

**Comment by linjieli222** [comment]
Closed due to inactivity.
